# Handy Codes

## import libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## set constraints on DataFrames

In [4]:
pd.set_option("display.max_colwidth", 30)
pd.set_option("display.max_rows", 30)
pd.set_option("display.max_columns", 30)
pd.set_option("display.precision", 30)

## commands

In [5]:
df = pd.read_csv('./data.csv')

In [6]:
df

5.1,3.5,1.4,0.2,Iris-setosa
0       4.9,3.0,1.4,0.2,Iris-setosa
1       4.7,3.2,1.3,0.2,Iris-setosa
2       4.6,3.1,1.5,0.2,Iris-setosa
3       5.0,3.6,1.4,0.2,Iris-setosa
4       5.4,3.9,1.7,0.4,Iris-setosa
..                              ...
144  6.7,3.0,5.2,2.3,Iris-virginica
145  6.3,2.5,5.0,1.9,Iris-virginica
146  6.5,3.0,5.2,2.0,Iris-virginica
147  6.2,3.4,5.4,2.3,Iris-virginica
148  5.9,3.0,5.1,1.8,Iris-virginica

[149 rows x 1 columns]

In [ ]:
x = np.empty((3,4), dtype=int)

In [5]:
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
x = np.full((3,4),55)

In [8]:
x

array([[55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55]])

In [9]:
python_list1 = [1, 2, 3, 4]

In [10]:
ndarray_1d = np.array(python_list1)

In [11]:
ndarray_1d

array([1, 2, 3, 4])